server:
  port: 9090
  readTimeout: 15s
  writeTimeout: 15s
  gracefulShutdown: 30s
logging:
  level: -1
  encoding: console
  development: true
jwt:
  secret: secret-key
  sessionTime: 86400s
db:
  dataSourceName: root:password@tcp(db)/local_db?charset=utf8&parseTime=True&multiStatements=true
  logLevel: 1
  migrate:
    enable: false
  pool:
    maxOpen: 10
    maxIdle: 5
    maxLifetime: 5m
metrics:
  namespace: article_server
  subsystem: