server:
  port: 8080
  readTimeout: 15s
  writeTimeout: 15s
  gracefulShutdown: 30s
logging:
  level: -1
  encoding: console
  development: true
jwt:
  secret: secret-key
  sessionTime: 86400s
db:
  dataSourceName: root:password@tcp(db)/local_db?charset=utf8&parseTime=True&multiStatements=true
  logLevel: 1
  migrate:
    enable: true
    dir: /config/migrations
  pool:
    maxOpen: 10
    maxIdle: 5
    maxLifetime: "5m"
cache:
  enabled: true
  prefix: article-
  type: redis
  ttl: 60s
  redis:
    cluster: true
    endpoints:
      - localhost:17000
    readTimeout: 3s
    writeTimeout: 3s
    dialTimeout: 5s
    poolSize: 10
    poolTimeout: 1m
    maxConnAge: 0
    idleTimeout: 5m
metrics:
  namespace: article_server
  subsystem: